zeppelin:
    image: dylanmei/zeppelin
    container_name: zeppelin
    environment:
        ZEPPELIN_PORT: 8080
        ZEPPELIN_JAVA_OPTS: >-
            -Dspark.driver.memory=1g
            -Dspark.executor.memory=2g
        MASTER: local[*]
    ports:
        - 8080:8080
    volumes:
        - /private/var/services/spark/zeppelin/data:/usr/zeppelin/data
        - /private/var/services/spark/zeppelin/notebook:/usr/zeppelin/notebook
